sample_rate = 16000  # Sample rate.
n_fft = 1024  # fft points (samples)
frame_shift = 0.0125  # seconds
frame_length = 0.05  # seconds
allow_clipping_in_normalization = True
hop_length = int(sample_rate * frame_shift)  # samples.
win_length = int(sample_rate * frame_length)  # samples.
n_mels = 256  # Number of Mel banks to generate
power = 1.5  # Exponent for amplifying the predicted magnitude
n_iter = 100  # Number of inversion iterations
preemphasis = .97  # or None
max_db = 100
min_db= -100
ref_db = 20
top_db = 15
